export const brands = [
  "Apple",
  "Microsoft",
  "Dell",
  "HP",
  "Lenovo",
  "Asus",
  "Acer",
  "Samsung",
  "Intel",
  "AMD",
  "Nvidia",
  "Western Digital",
  "Seagate",
  "Corsair",
  "Logitech",
  "Razer",
  "Sony",
  "Toshiba",
  "IBM",
  "Google",
  "Huawei",
];

export const categories = [
  "Desktop Computers",
  "Laptop Computers",
  "Monitors",
  "Keyboards",
  "Mice",
  "Printers",
  "External Hard Drives",
  "Networking Devices",
  "Routers",
  "Switches",
  "Graphics Cards",
  "RAM/Memory Modules",
  "Power Supplies",
  "Computer Cases/Towers",
  "Webcams",
  "Speakers",
  "Headsets",
  "Microphones",
  "UPS (Uninterruptible Power Supply)",
  "Docking Stations",
];

